# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
testpkg1 <- function() {
    invisible(.Call('_pkg2_testpkg1', PACKAGE = 'pkg2'))
}

rcpp_hello_world <- function() {
    .Call('_pkg2_rcpp_hello_world', PACKAGE = 'pkg2')
}

