// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// call_pkg1_from_pkg2
void call_pkg1_from_pkg2();
RcppExport SEXP _pkg2_call_pkg1_from_pkg2() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call_pkg1_from_pkg2();
    return R_NilValue;
END_RCPP
}
// call_pkg1_class_from_pkg2
void call_pkg1_class_from_pkg2(int id);
RcppExport SEXP _pkg2_call_pkg1_class_from_pkg2(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    call_pkg1_class_from_pkg2(id);
    return R_NilValue;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _pkg2_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pkg2_call_pkg1_from_pkg2", (DL_FUNC) &_pkg2_call_pkg1_from_pkg2, 0},
    {"_pkg2_call_pkg1_class_from_pkg2", (DL_FUNC) &_pkg2_call_pkg1_class_from_pkg2, 1},
    {"_pkg2_rcpp_hello_world", (DL_FUNC) &_pkg2_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_pkg2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
