// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/pkg1.h"
#include "../inst/include/pkg1_types.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// makeClass1
void makeClass1(int id);
static SEXP _pkg1_makeClass1_try(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    makeClass1(id);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _pkg1_makeClass1(SEXP idSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_pkg1_makeClass1_try(idSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _pkg1_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("void(*makeClass1)(int)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _pkg1_RcppExport_registerCCallable() { 
    R_RegisterCCallable("pkg1", "_pkg1_makeClass1", (DL_FUNC)_pkg1_makeClass1_try);
    R_RegisterCCallable("pkg1", "_pkg1_RcppExport_validate", (DL_FUNC)_pkg1_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_pkg1_makeClass1", (DL_FUNC) &_pkg1_makeClass1, 1},
    {"_pkg1_RcppExport_registerCCallable", (DL_FUNC) &_pkg1_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_pkg1(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
