// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_pkg1_H_GEN_
#define RCPP_pkg1_H_GEN_

#include "pkg1_RcppExports.h"

#endif // RCPP_pkg1_H_GEN_
