// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_pkg1_RCPPEXPORTS_H_GEN_
#define RCPP_pkg1_RCPPEXPORTS_H_GEN_

#include "pkg1_types.h"
#include <Rcpp.h>

namespace pkg1 {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("pkg1", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("pkg1", "_pkg1_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in pkg1");
            }
        }
    }

    inline void makeClass1(int id) {
        typedef SEXP(*Ptr_makeClass1)(SEXP);
        static Ptr_makeClass1 p_makeClass1 = NULL;
        if (p_makeClass1 == NULL) {
            validateSignature("void(*makeClass1)(int)");
            p_makeClass1 = (Ptr_makeClass1)R_GetCCallable("pkg1", "_pkg1_makeClass1");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_makeClass1(Shield<SEXP>(Rcpp::wrap(id)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

}

#endif // RCPP_pkg1_RCPPEXPORTS_H_GEN_
