# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
makeClass1 <- function(id) {
    invisible(.Call('_pkg1_makeClass1', PACKAGE = 'pkg1', id))
}

